Added thread for message processing
serilog-contrib/serilog-sinks-richtextbox pull request #14
Opened 2021-08-27 20:12 UTC by Skaptor

I took the embedded state machine approach and made a state machine based thread that waits roughly 25ms or a message counter to reach a certain batch size for reducing the amount of dispatcher calls. I ran the tests and nothing broke 👍. It is noticeable faster than calling the dispatcher method for each message that is being logged. All suggestions are accepted.

2021-09-04 17:52 UTC, augustoproiete requested changes
Thanks for the PR :+1:. Added a few comments

2021-09-04 17:52 UTC, augustoproiete commented on src/Serilog.Sinks.RichTextBox.Wpf/Sinks/RichTextBox/RichTextBoxSink.cs
> +            MessageQueue.Enqueue(writer.ToString());
We're getting a build error here. Could you take a look / amend / force push?

2021-09-04 17:52 UTC, augustoproiete commented on src/Serilog.Sinks.RichTextBox.Wpf/Sinks/RichTextBox/RichTextBoxSink.cs
> +                        if (MessageQueue.TryDequeue(out line) == false)
We're getting a build error here. Could you take a look / amend / force push?

2021-09-04 17:52 UTC, augustoproiete commented on src/Serilog.Sinks.RichTextBox.Wpf/Sinks/RichTextBox/RichTextBoxSink.cs
> +            _consumerThread = new Thread(new ThreadStart(ProcessMessages){ IsBackground = true });
We're getting a build error here. Could you take a look / amend / force push?

2021-09-04 17:52 UTC, augustoproiete commented on src/Serilog.Sinks.RichTextBox.Wpf/Sinks/RichTextBox/RichTextBoxSink.cs
> +            StringWriter writer = new();
I think we should enqueue the log events directly, and do the rendering on the background thread, so that `Emit` returns as fast as possible

2021-09-08 18:40 UTC, Skaptor commented
Sure I'll make the adjustments. I maybe broke something because I used the vscode web version

2021-10-04 14:21 UTC, Skaptor commented on src/Serilog.Sinks.RichTextBox.Wpf/Sinks/RichTextBox/RichTextBoxSink.cs
> +            StringWriter writer = new();
Hello, I'm not quite sure what you mean here... Should emit not queue the messages?

2021-10-04 14:28 UTC, augustoproiete commented on src/Serilog.Sinks.RichTextBox.Wpf/Sinks/RichTextBox/RichTextBoxSink.cs
> +            StringWriter writer = new();
Hi, I mean that the allocation of the `StringWriter` and the formatting of the message should (ideally) happen in the background thread if possible, so that the _only_ thing that `Emit` does is to enqueue the message to be processed later in the background thread

2021-10-04 14:49 UTC, Skaptor commented on src/Serilog.Sinks.RichTextBox.Wpf/Sinks/RichTextBox/RichTextBoxSink.cs
> +            StringWriter writer = new();
OK I think I made it work now. Please check the latest commit.

2021-10-18 11:51 UTC, TonyValenti commented
Hi!  What's the status of this?  Really hoping for an update.

2021-10-18 22:35 UTC, TonyValenti commented
@augustoproiete - can you publish an updated nuget package I can use?

2021-12-01 19:17 UTC, Skaptor commented
Hello, is there any new update on this?

2021-12-03 23:19 UTC, TonyValenti commented
When will this be committed?

@augustoproiete - If you're not able to maintain this project, can you make me an admin?  I have a vested interest in this being advanced.

2021-12-04 00:47 UTC, Skaptor commented
@TonyValenti did you try the artifact nupkg? how did it work?

2021-12-04 01:59 UTC, augustoproiete commented
@TonyValenti See messages above - This needs manual testing, didn't hear back from you since Oct 18th https://github.com/serilog-contrib/serilog-sinks-richtextbox/pull/14#issuecomment-946244158

2021-12-06 14:26 UTC, TonyValenti commented
Thanks!  I'll grab the source and do a deep test later today/tomorrow.

2021-12-08 02:42 UTC, augustoproiete commented
@TonyValenti How did the test go? I imagine merging this will have an impact on https://github.com/serilog-contrib/serilog-sinks-richtextbox/pull/32 so might be good to get this one merged first and release a new preview

2021-12-08 02:50 UTC, TonyValenti commented
I wasn't able to figure out how to test it without it being merged. Please merge then I'll review and resolve any issues. 

My changes on my PR are minimal to existing code and I'd be surprised if there were any issues that took longer than a second to resolve.

2021-12-08 02:54 UTC, augustoproiete commented
@TonyValenti Download the NuGet package is [here](https://github.com/serilog-contrib/serilog-sinks-richtextbox/actions/runs/1356841274) (package artifact), unzip into a [local feed](https://docs.microsoft.com/en-us/nuget/hosting-packages/local-feeds)/folder

2021-12-08 03:16 UTC, TonyValenti commented
This works great.

2021-12-08 03:49 UTC, augustoproiete approved these changes
LGTM

2021-12-08 03:50 UTC, merged

2021-12-08 03:50 UTC, augustoproiete commented
@Skaptor your changes have been merged, thanks for your contribution :+1:

2021-12-08 16:21 UTC, Skaptor commented
@augustoproiete Happy to help. Thank you for this sink!